### ISSUE TITLE
Cannot compile model

### ISSUE THREAD

**Issue by joverwey** [kazum/tvm-wasm#2]
The first problem I had was that the constants defined in c_runtime_api.rs  do not match those used in packed_func.rs.

I was able to fix this by renaming the constants in packed_func.rs. For example:
```
TVMTypeCode_kTVMNullptr becomes TVMArgTypeCode_kTVMNullptr
```
This seemed to fix the problem and I was able to compile the Rust runtime to WASM.
I ran into another problem with the Python code though when trying to compile the model:
```
johan@DESKTOP-8DKNGPA:/mnt/d/repos/tvm-wasm$ AR=llvm-ar-9 python3 build_lib.py -O3 resnet50v1.onnx
WARNING:root:Attribute momentum is ignored in relay.sym.batch_norm
...
WARNING:root:Attribute spatial is ignored in relay.sym.batch_norm
Traceback (most recent call last):
  File "build_lib.py", line 71, in <module>
    build_lib(args.model_file, args.opt_level)
  File "build_lib.py", line 38, in build_lib
    graph, lib, params = relay.build_module.build(net, target, params=params)
  File "/mnt/d/repos/incubator-tvm/python/tvm/relay/build_module.py", line 238, in build
    target = _update_target(target)
  File "/mnt/d/repos/incubator-tvm/python/tvm/relay/build_module.py", line 45, in _update_target
    tgts[dev_type] = _target.create(target)
  File "/mnt/d/repos/incubator-tvm/python/tvm/target/target.py", line 355, in create
    return _ffi_api.TargetFromString(target_str)
  File "/mnt/d/repos/incubator-tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 225, in __call__
    raise get_last_ffi_error()
AttributeError: Traceback (most recent call last):
  [bt] (5) /mnt/d/repos/incubator-tvm/build/libtvm.so(TVMFuncCall+0x65) [0x7f4f9fe0a975]
  [bt] (4) /mnt/d/repos/incubator-tvm/build/libtvm.so(+0x11f2a4b) [0x7f4f9f8b9a4b]
  [bt] (3) /mnt/d/repos/incubator-tvm/build/libtvm.so(tvm::Target::Create(tvm::runtime::String const&)+0x388) [0x7f4f9f8b95f8]
  [bt] (2) /mnt/d/repos/incubator-tvm/build/libtvm.so(tvm::Target::CreateTarget(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x336) [0x7f4f9f8b6ec6]
  [bt] (1) /mnt/d/repos/incubator-tvm/build/libtvm.so(tvm::TargetKindNode::ParseAttrsFromRaw(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const+0xe36) [0x7f4f9f8c0e76]
  [bt] (0) /mnt/d/repos/incubator-tvm/build/libtvm.so(+0x11f7812) [0x7f4f9f8be812]
  system-lib
  model
  mcpu
  device
  keys
  libs
  mattr
  mtriple
  mfloat-abi
  File "/mnt/d/repos/incubator-tvm/src/target/target_kind.cc", line 273
AttributeError: Invalid config option, cannot recognize 'target'. Candidates are:
```

Could this be a similiar problem where the FFI symbols in Python does not match those in Rust?

I am running this on Ubuntu 18.04 with LLVM 9.

**Comment by joverwey** [comment]
This was caused by my TVM_HOME environment variable set to the wrong version of TVM.
